version: '3'
services:
    mongo:
        image: mongo
        env_file:
          - .env
        container_name: apidbs
        environment:
        - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        volumes:
          - ./mongo:/data/db
        ports:
          - "27017:27017"
    cache:
      image: redis:6.2-alpine
      container_name:  redis
      restart: always
      ports:
        - '6379:6379'
      command: redis-server --save 20 1 --loglevel warning
      volumes:
        - cache:/data
volumes:
  mongo:
    driver: local
  cache:
    driver: local
